// <auto-generated />
namespace ControlActividades.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Refactorizacion_Dos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Refactorizacion_Dos));
        
        string IMigrationMetadata.Id
        {
            get { return "202512140000398_Refactorizacion_Dos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
